GET http://localhost:3030/crawler/DayCurrency HTTP/1.1
content-type: application/json

{
    "day": "21-09-2018"
}

###

GET http://localhost:3030/crawler HTTP/1.1

###

POST http://localhost:3030/crawler/PeriodCurrency HTTP/1.1
content-type: application/json

{
    "start": "17-10-2018",
    "end": "18-10-2018"
} 